; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s16
Gui Add, Edit, x560 y248 w33 h30 vLvl, %lvl% 20
Gui Font
Gui Font, s15
Gui Add, Edit, x16 y248 w530 h31 vLink, %Link% https://www.d20pfsrd.com/classes/core-classes/fighter/
Gui Font
Gui Font, s15
Gui Add, Link, x16 y288 w150 h33, <a href="https://pathinator.netlify.com/">Pathinator.com</a>
Gui Font
Gui Add, Picture, x-8 y-8 w627 h247, logo.png
Gui Add, Button, x224 y288 w149 h26 gCreate, Create

Gui Show, w609 h326, Window
Return

Create:
GuiControlGet, Link
GuiControlGet, Lvl
; msgbox, pathfinder.exe %Link% %Lvl%
Run, pathfinder.exe %link% %lvl%


GuiEscape:
GuiClose:
    ExitApp